// Export file paths as object keys so Webpack can bundle them
export default {
    AFC: require('./nfl/nfl-afc.png'),
    NFC: require('./nfl/nfl-nfc.png'),
    NFL: require('./nfl/nfl-league-logo.png'),
    //////////
    ARI: require('./nfl/nfl-arizona-cardinals.png'),
    ATL: require('./nfl/nfl-atlanta-falcons.png'),
    BAL: require('./nfl/nfl-baltimore-ravens.png'),
    BUF: require('./nfl/nfl-buffalo-bills.png'),
    CAR: require('./nfl/nfl-carolina-panthers.png'),
    CHI: require('./nfl/nfl-chicago-bears.png'),
    CIN: require('./nfl/nfl-cincinnati-bengals.png'),
    CLE: require('./nfl/nfl-cleveland-browns.png'),
    DAL: require('./nfl/nfl-dallas-cowboys.png'),
    DEN: require('./nfl/nfl-denver-broncos.png'),
    DET: require('./nfl/nfl-detroit-lions.png'),
    GB: require('./nfl/nfl-green-bay-packers.png'),
    HOU: require('./nfl/nfl-houston-texans.png'),
    IND: require('./nfl/nfl-indianapolis-colts.png'),
    JAX: require('./nfl/nfl-jacksonville-jaguars.png'),
    KC: require('./nfl/nfl-kansas-city-chiefs.png'),
    LAC: require('./nfl/nfl-los-angeles-chargers.png'),
    LAR: require('./nfl/nfl-los-angeles-rams.png'),
    MIA: require('./nfl/nfl-miami-dolphins.png'),
    MIN: require('./nfl/nfl-minnesota-vikings.png'),
    NE: require('./nfl/nfl-new-england-patriots.png'),
    NO: require('./nfl/nfl-new-orleans-saints.png'),
    NYG: require('./nfl/nfl-new-york-giants.png'),
    NYJ: require('./nfl/nfl-new-york-jets.png'),
    OAK: require('./nfl/nfl-oakland-raiders.png'),
    PHI: require('./nfl/nfl-philadelphia-eagles.png'),
    PIT: require('./nfl/nfl-pittsburgh-steelers.png'),
    SEA: require('./nfl/nfl-seattle-seahawks.png'),
    SF: require('./nfl/nfl-san-francisco-49ers.png'),
    TB: require('./nfl/nfl-tampa-bay-buccaneers.png'),
    TEN: require('./nfl/nfl-tennessee-titans.png'),
    WAS: require('./nfl/nfl-washington-redskins.png')
  };